name: Build & Deploy Docs

on:
  push:
    branches: [master]
    paths:
      - "docs/**"
      - "README.md"
      - "docs.yml"

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sphinx furo sphinx-autodoc-typehints sphinxcontrib-httpdomain myst-nb

      - name: Build HTML
        run: sphinx-build -b html docs docs/_build/html

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/_build/html

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
