name: Build & Deploy Docs

on:
  push:
    branches:
      - master

permissions:
  contents: write   # для checkout и пуша
  pages: write      # для GitHub Pages
  id-token: write   # необязательно, но по умолчанию даётся

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Забираем код
      - uses: actions/checkout@v4
        with:
          persist-credentials: true  # чтобы GITHUB_TOKEN сохранился

      # 2. Устанавливаем Python и MkDocs
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          pip install mkdocs-material

      # 3. Сборка сайта в папку docs/
      - name: Build MkDocs site
        run: mkdocs build --strict

      # 4. Коммитим и пушим сгенерированные файлы из docs/
      - name: Commit and push Docs
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions[bot]
          author_email: github-actions[bot]@users.noreply.github.com
          message: "chore(docs): update site"
          add: "docs"