name: Build & Deploy Sphinx Docs

# Запускаем при пуше в master (или main), и по PR
on:
  push:
    branches: [ master ]
  pull_request:

# Нужные права для записи в gh-pages
permissions:
  contents: read       # для checkout
  pages: write         # для деплоя Pages
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install sphinx sphinx-rtd-theme

      - name: Build HTML docs
        working-directory: docs
        run: sphinx-build -b html . _build/html

      # Конфигурируем GitHub Pages
      - name: Configure GitHub Pages
        uses: actions/configure-pages@v3

      # Аплоадим сгенерированный сайт
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: docs/_build/html

      # Деплойим
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
