on:
  push:
    branches:
      - master

permissions:
  contents: read          # для checkout
  pages: write            # чтобы иметь право пушить в gh-pages
  id-token: write         # необязательно для этого экшена, но полезно для future needs

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      # 1) Клонируем репо
      - uses: actions/checkout@v4

      # 2) Устанавливаем Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # 3) Устанавливаем зависимости (MkDocs + тема)
      - name: Install dependencies
        run: |
          pip install mkdocs-material

      # 4) Сборка сайта
      - name: Build site
        run: mkdocs build --strict --site-dir site

      # 5) Деплой в ветку gh-pages
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: gh-pages        # ветка, куда пушим
          folder: site            # папка с готовым сайтом
          clean: true             # удалять всё в gh-pages перед пушем
          token: ${{ secrets.GITHUB_TOKEN }}