name: Build & Deploy Sphinx Docs

on:
  push:
    branches: [ master ]
  workflow_dispatch:

permissions:
  pages: write         # deploy-pages needs this
  id-token: write      # for deploy-pages authentication

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      artifact-path: ${{ steps.upload-artifact.outputs.artifact-path }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install docs dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sphinx furo sphinx-rtd-theme

      - name: Build Sphinx HTML
        run: |
          cd docs
          sphinx-build -b html . _build/html

      - name: Upload pages artifact
        id: upload-artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/_build/html

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
