name: Build & Deploy Sphinx docs

on:
  push:
    branches: [main]          # генерировать сайт при каждом пуше в main
    paths:
      - "docs/**"             # или добавь *.py, README.md и т.д.

permissions:
  contents: write             # нужно для публикации Pages
  pages: write
  id-token: write

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt sphinx sphinx-rtd-theme

      - name: Build HTML
        run: |
          cd docs
          make html

      # загружаем артефакт Pages
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/_build/html

      # деплой на GitHub Pages
      - name: Deploy to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v4   # официальный экшен
