# .github/workflows/deploy-docs.yml
name: Build & Deploy Sphinx Docs

on:
  push:
    branches:
      - master     # или main — ветка, куда пушите код

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          pip install sphinx sphinx-rtd-theme furo

      - name: Build Sphinx HTML
        run: |
          sphinx-build -b html docs docs/_build/html

      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: docs/_build/html

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write       # чтобы пушить в репо
      pages: write          # право на GitHub Pages
      id-token: write

    steps:
      - name: Download pages artifact
        uses: actions/download-pages-artifact@v2

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v3
        with:
          publish_branch: master      # куда развернуть Pages
          publish_dir: docs/_build/html

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
